import { useCallback, useEffect, useState } from 'react'
import { addToAuditPack, fetchAuditReport, generateInvestigationAnalysis, removeFromAuditPack } from '../../api/client'
import type { AnalysisJob, AuditEventSummary, AuditPackReview, AuditReport, EvidenceObject, StructuredAnalysisAssessment } from '../../api/types'
import { Button } from '../ui/Button'
import { AnalysisProgress } from './AnalysisProgress'

function EvidenceList({ title, items }: { title: string; items: EvidenceObject[] }) {
  return <section className="rounded border border-border bg-panel p-4"><h3 className="mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-text-muted">{title}</h3>{items.length ? <ul className="space-y-2 text-xs">{items.map((item) => <li key={item.evidence_id ?? item.evidenceId}><span className="mr-2 font-mono text-accent">{item.evidence_id ?? item.evidenceId}</span>{item.observation}<span className="ml-2 text-text-faint">({item.source})</span></li>)}</ul> : <p className="text-xs text-text-faint">No structured evidence available.</p>}</section>
}

function ReviewRow({ eventId, event, review, onSave, onRemove }: { eventId: string; event: AuditEventSummary; review: AuditPackReview; onSave: (eventId: string, note: string, disposition: string) => void; onRemove: (eventId: string) => void }) {
  const [note, setNote] = useState(review.note)
  const [disposition, setDisposition] = useState(review.disposition)
  return <article className="break-inside-avoid border-l-2 border-accent pl-3 text-xs"><div className="font-mono text-accent">{event.eventId}</div><div>{event.firstDetection.slice(0, 10)} -&gt; {event.lastDetection.slice(0, 10)} · {event.observationCount} observations · {event.triage.state}</div><div className="mt-1 text-text-muted print:block">Human disposition: {review.disposition || 'Not recorded'}{review.note && ` · ${review.note}`}</div><div className="mt-2 flex flex-wrap gap-2 print:hidden"><select aria-label={`Disposition for ${eventId}`} value={disposition} onChange={(e) => setDisposition(e.target.value)} className="rounded border border-border-strong bg-bg px-2 py-1 text-xs"><option value="">No disposition</option><option value="VERIFY">VERIFY</option><option value="INSUFFICIENT">INSUFFICIENT</option><option value="NO_FURTHER_ACTION">NO FURTHER ACTION</option><option value="UNRESOLVED">UNRESOLVED</option></select><input aria-label={`Note for ${eventId}`} value={note} onChange={(e) => setNote(e.target.value)} placeholder="Optional human note" className="min-w-[220px] flex-1 rounded border border-border-strong bg-bg px-2 py-1 text-xs" /><Button onClick={() => onSave(eventId, note, disposition)}>SAVE REVIEW</Button><Button onClick={() => onRemove(eventId)}>REMOVE FROM PACKAGE</Button></div></article>
}

function AssessmentSummary({ assessment }: { assessment: StructuredAnalysisAssessment }) {
  return <div className="space-y-2"><div className="font-semibold text-accent">{assessment.role}</div>{assessment.findings.map((finding) => <div key={finding.hypothesis_id} className="break-inside-avoid border-t border-border/60 pt-2 text-[11px]"><div className="flex justify-between gap-2"><span className="font-mono">{finding.hypothesis_id}</span><span>{finding.support_score}/100 · {finding.evidence_sufficiency}</span></div><p className="mt-1 text-text-muted">{finding.summary}</p><p className="mt-1 font-mono text-[10px] text-text-faint">+ {finding.supporting_evidence_ids.join(', ') || 'n/a'} · − {finding.contradicting_evidence_ids.join(', ') || 'n/a'}</p></div>)}</div>
}

function EvidenceReferences({ label, ids, evidenceById }: { label: string; ids: string[]; evidenceById: Map<string, EvidenceObject> }) {
  const items = ids.map((id) => ({ id, item: evidenceById.get(id) })).filter((entry): entry is { id: string; item: EvidenceObject } => Boolean(entry.item))
  if (!items.length) return null
  return <div className="mt-2 rounded border border-border/60 bg-panel-raised/40 p-2"><div className="text-[10px] font-semibold uppercase tracking-wider text-text-faint">{label}</div>{items.map(({ id, item }) => <p key={id} className="mt-1 text-[10px] text-text-muted"><span className="mr-1 font-mono text-accent">{id}</span>{item.observation} <span className="text-text-faint">({item.source})</span></p>)}</div>
}

function AnalysisValidationNotice({ report }: { report: AuditReport }) {
  const mixed = report.aiAnalysis.filter(({ analysis }) => analysis.validation_status === 'VALID_WITH_AMBIGUITY')
  if (!mixed.length) return null
  const mixedIds = [...new Set(mixed.flatMap(({ analysis }) => analysis.final_assessment.investigator.findings.flatMap((finding) => finding.mixed_evidence_ids ?? [])))]
  return <div className="mb-3 rounded border border-status-moderate/40 bg-status-moderate/10 p-3 text-text-muted">ANALYSIS COMPLETE · MIXED EVIDENCE. The available evidence does not clearly resolve every hypothesis. Investigator and Skeptic interpretations are shown below.{mixedIds.length > 0 && <span className="ml-1 font-mono text-[10px]">Mixed evidence: {mixedIds.join(', ')}</span>}</div>
}

function MainFindings({ report }: { report: AuditReport }) {
  const evidenceById = new Map(report.deterministicEvidence.flatMap((group) => [...group.observed, ...group.derived].map((item) => [item.evidence_id ?? item.evidenceId, item] as const)).filter(([id]) => Boolean(id))) as Map<string, EvidenceObject>
  return <section data-testid="main-findings" className="break-inside-avoid rounded border border-accent/50 bg-panel p-4 text-xs"><div className="mb-3 flex items-baseline justify-between gap-3"><div><h2 className="text-sm font-semibold">Main findings</h2><p className="mt-1 text-text-muted">Final hypotheses and assessments from the explicit Investigator / Skeptic analysis.</p></div><span className="shrink-0 font-mono text-[10px] text-text-faint">AI interpretation · evidence-linked</span></div>{report.aiAnalysis.length === 0 ? <p className="rounded border border-border bg-bg/60 p-3 text-text-muted">No Investigator/Skeptic analysis has been run for the selected FireEvents. This report does not fabricate an AI assessment.</p> : <div className="space-y-4">{report.aiAnalysis.map(({ eventId, analysis }) => <article key={eventId} className="break-inside-avoid rounded border border-border bg-bg/60 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-mono font-semibold text-accent">{eventId}</h3><span className="text-[10px] uppercase tracking-wider text-text-faint">{analysis.status} · {analysis.algorithm_version}</span></div><div className="mt-3 grid gap-4 md:grid-cols-2"><div><AssessmentSummary assessment={analysis.final_assessment.investigator} />{analysis.final_assessment.investigator.findings.map((finding) => <div key={`${finding.hypothesis_id}-investigator-evidence`}><EvidenceReferences label="Supporting evidence" ids={finding.supporting_evidence_ids} evidenceById={evidenceById} /><EvidenceReferences label="Contradicting evidence" ids={finding.contradicting_evidence_ids} evidenceById={evidenceById} /></div>)}</div><div><AssessmentSummary assessment={analysis.final_assessment.skeptic} />{analysis.final_assessment.skeptic.findings.map((finding) => <div key={`${finding.hypothesis_id}-skeptic-evidence`}><EvidenceReferences label="Supporting evidence" ids={finding.supporting_evidence_ids} evidenceById={evidenceById} /><EvidenceReferences label="Contradicting evidence" ids={finding.contradicting_evidence_ids} evidenceById={evidenceById} /></div>)}</div></div></article>)}</div>}{report.analysisNotRunEventIds.length > 0 && <p className="mt-3 text-text-muted">{report.analysisNotRunEventIds.length} selected FireEvent(s) remain explicitly not run and are not represented by an invented assessment.</p>}</section>
}

function StructuredAnalysisReport({ report, generatingEventId, analysisStartedAt, analysisStage, error, onGenerate }: { report: AuditReport; generatingEventId: string | null; analysisStartedAt?: string; analysisStage?: string | null; error: string; onGenerate: (eventId: string) => void }) {
  return <section className="break-inside-avoid rounded border border-border bg-panel p-4 text-xs"><h2 className="mb-2 text-sm font-semibold">Analysis record and verification</h2><AnalysisValidationNotice report={report} />{generatingEventId && analysisStartedAt && <AnalysisProgress startedAt={analysisStartedAt} stage={analysisStage} returnMessage="The job keeps running if you leave this report. Return to it to see the result." />}{report.analysisNotRunEventIds.length > 0 && <div className="space-y-2"><div className="font-semibold">Analysis not run</div>{report.analysisNotRunEventIds.map((eventId) => <div key={eventId} className="flex items-center justify-between gap-3 rounded border border-border bg-bg/60 p-2"><span className="font-mono text-text-muted">{eventId}</span><Button variant="primary" className="shrink-0 text-[10px] print:hidden" disabled={generatingEventId !== null} onClick={() => onGenerate(eventId)}>{generatingEventId === eventId ? 'GENERATING...' : 'GENERATE INVESTIGATION ANALYSIS'}</Button></div>)}</div>}{error && <div role="alert" className="mt-3 rounded border border-status-urgent/40 bg-status-urgent/10 p-2 text-red-200">{error}</div>}{report.unresolvedQuestions.length > 0 && <div className="mt-3"><div className="font-semibold">Unresolved disagreement</div>{report.unresolvedQuestions.map((question, index) => <p key={`${question.eventId}-${index}`} className="mt-1 text-text-muted">{question.eventId}: {question.question} <span className="font-mono text-text-faint">({question.evidence_ids.join(', ')})</span></p>)}</div>}{report.verificationRecommendations.length > 0 && <div className="mt-3"><div className="font-semibold">Targeted verification questions</div>{report.verificationRecommendations.slice(0, 3).map((question, index) => <p key={`${question.eventId}-${index}`} className="mt-1 text-text-muted">{question.eventId}: {question.question}</p>)}</div>}<p className="mt-3 text-[10px] text-text-faint">AI interpretation is separate from deterministic evidence and human review. Evidence IDs are retained with each finding; no chain-of-thought is shown.</p></section>
}

export function AuditReportView({ auditId, onBack }: { auditId: string; onBack: () => void }) {
  const [report, setReport] = useState<AuditReport | null>(null)
  const [error, setError] = useState('')
  const [generatingEventId, setGeneratingEventId] = useState<string | null>(null)
  const [analysisError, setAnalysisError] = useState('')
  const [analysisStartedAt, setAnalysisStartedAt] = useState<string>()
  const [analysisStage, setAnalysisStage] = useState<string | null>(null)
  const loadReport = useCallback(async () => { setError(''); try { setReport(await fetchAuditReport(auditId)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Report could not be loaded.') } }, [auditId])
  useEffect(() => { void loadReport() }, [loadReport])
  if (error) return <div role="alert" className="p-6 text-sm text-red-200"><div>{error}</div><Button className="mt-3" onClick={() => void loadReport()}>RETRY REPORT</Button></div>
  if (!report) return <div role="status" className="p-6 text-sm text-text-muted">Loading engagement report...</div>
  const currentReport = report
  async function saveReview(eventId: string, note: string, disposition: string) { try { const review = await addToAuditPack(auditId, eventId, { note, disposition }); setReport({ ...currentReport, selectedFireEvents: currentReport.selectedFireEvents.map((item) => item.event.eventId === eventId ? { ...item, review } : item), humanNotes: currentReport.humanNotes.map((item) => item.eventId === eventId ? review : item) }) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Human review could not be saved.') } }
  async function generateAnalysis(eventId: string) { setGeneratingEventId(eventId); setAnalysisStartedAt(new Date().toISOString()); setAnalysisStage('Starting'); setAnalysisError(''); try { await generateInvestigationAnalysis(auditId, eventId, (job: AnalysisJob) => { setAnalysisStage(job.stage ?? 'Starting'); if (job.startedAt) setAnalysisStartedAt(job.startedAt) }); await loadReport() } catch { setAnalysisError('Analysis could not be completed. Your evidence and previous analysis have been preserved. Retry analysis.') } finally { setGeneratingEventId(null) } }
  async function removeFromPackage(eventId: string) { try { await removeFromAuditPack(auditId, eventId); await loadReport() } catch (reason) { setError(reason instanceof Error ? reason.message : 'FireEvent could not be removed from the audit package.') } }
  return <div className="h-full overflow-auto bg-bg p-5 text-text print:h-auto print:overflow-visible print:bg-white print:p-0 print:text-black"><div className="mx-auto max-w-6xl space-y-4">
    <div className="break-inside-avoid flex items-start justify-between"><div><div className="text-[10px] uppercase tracking-[0.2em] text-accent">Environmental Fire Review / Investigation Pack</div><h1 className="mt-1 text-xl font-semibold">Engagement report</h1><p className="text-xs text-text-muted">Audit scope · {report.auditScope.reviewStart} -&gt; {report.auditScope.reviewEnd}</p></div><div className="flex gap-2 print:hidden"><Button onClick={() => window.print()}>DOWNLOAD PDF</Button><Button onClick={onBack}>RETURN TO MAP</Button></div></div>
    <div className="grid grid-cols-3 gap-2 text-center text-xs sm:grid-cols-6">{Object.entries(report.counts).map(([label, value]) => <div key={label} className="break-inside-avoid rounded border border-border bg-panel p-3"><div className="text-xl font-semibold text-accent">{value}</div><div className="uppercase tracking-wider text-text-faint">{label}</div></div>)}</div>
    <section className="break-inside-avoid grid gap-3 md:grid-cols-2"><div className="rounded border border-border bg-panel p-4 text-xs"><h2 className="mb-2 font-semibold">Source and method</h2><p><span className="text-text-muted">Observed:</span> {report.sourceMethodSummary.observed}</p><p className="mt-1"><span className="text-text-muted">Derived:</span> {report.sourceMethodSummary.derived}</p><p className="mt-1"><span className="text-text-muted">AI interpretation:</span> {report.sourceMethodSummary.ai}</p></div><div className="rounded border border-border bg-panel p-4 text-xs"><h2 className="mb-2 font-semibold">Review scope</h2><div className="grid grid-cols-2 gap-2"><div><span className="text-text-muted">FIRMS observations</span><div className="font-semibold text-accent">{report.compressionSummary.qualifiedObservations?.toLocaleString() ?? '-'}</div></div><div><span className="text-text-muted">FireEvents</span><div className="font-semibold text-accent">{report.compressionSummary.fireEvents?.toLocaleString() ?? '-'}</div></div><div><span className="text-text-muted">In scope + buffer</span><div className="font-semibold text-accent">{report.compressionSummary.inScopeAndBuffer?.toLocaleString() ?? '-'}</div></div><div><span className="text-text-muted">Review queue</span><div className="font-semibold text-accent">{report.compressionSummary.requiringHumanReview?.toLocaleString() ?? '-'}</div></div><div><span className="text-text-muted">Selected</span><div className="font-semibold text-accent">{report.compressionSummary.selected?.toLocaleString() ?? '-'}</div></div></div><p className="mt-2 text-text-muted">Stage-1 classifies fire support; it is not expected to compress FIRMS-only haze-season data.</p></div></section>
    <MainFindings report={report} />
    <section className="break-inside-avoid rounded border border-border bg-panel p-4"><h2 className="mb-3 text-sm font-semibold">Selected FireEvents</h2>{report.selectedFireEvents.length ? <div className="space-y-3">{report.selectedFireEvents.map(({ event, review }) => <ReviewRow key={event.eventId} eventId={event.eventId} event={event} review={review} onSave={saveReview} onRemove={(eventId) => void removeFromPackage(eventId)} />)}</div> : <p className="text-xs text-text-faint">No FireEvents have been added to this pack.</p>}</section>
    <section className="break-inside-avoid rounded border border-border bg-panel p-4 text-xs"><h2 className="mb-2 text-sm font-semibold">Maps and chronology</h2><p>Map handoff contains {report.maps.selectedEventIds.length} selected FireEvent(s); {report.graphRelationships.length} deterministic graph relationship(s) are retained.</p>{report.chronology.map((item) => <div key={item.eventId} className="mt-2 font-mono text-text-muted">{item.firstDetection.slice(0, 10)} - {item.lastDetection.slice(0, 10)} · {item.eventId}</div>)}</section>
    <section data-testid="evidence-log" className="break-before-page space-y-3"><div className="rounded border border-border bg-panel p-4 text-xs"><h2 className="text-sm font-semibold">Comprehensive evidence log</h2><p className="mt-1 text-text-muted">Observed and derived evidence for the selected FireEvents, retained with evidence IDs and source references.</p></div>{report.deterministicEvidence.map((item) => <div key={item.eventId} className="space-y-3"><EvidenceList title={`Observed evidence · ${item.eventId}`} items={item.observed} /><EvidenceList title={`Derived metrics · ${item.eventId}`} items={item.derived} /></div>)}</section>
    <StructuredAnalysisReport report={report} generatingEventId={generatingEventId} analysisStartedAt={analysisStartedAt} analysisStage={analysisStage} error={analysisError} onGenerate={(eventId) => void generateAnalysis(eventId)} />
    <section className="break-inside-avoid rounded border border-border bg-panel p-4 text-xs"><h2 className="mb-2 text-sm font-semibold">Limitations, provenance and model versions</h2>{report.limitations.map((item) => <p key={item} className="mb-1 text-text-muted">- {item}</p>)}<p className="mt-2 font-mono text-text-faint">{report.provenance.algorithmVersions.join(' · ')}</p></section>
    <p className="break-inside-avoid rounded border border-status-moderate/40 bg-status-moderate/10 p-4 text-xs text-text-muted">{report.disclaimer}</p>
  </div></div>
}
